project_id = "qgwapsjdpoxoyyriflzz"

[functions.aircall-dial]
verify_jwt = false

[functions.google-calendar-event]
verify_jwt = false

[functions.google-oauth-exchange]
verify_jwt = false

[functions.google-calendar-busy]
verify_jwt = false
